In [1]:
import pandas as pd
import pandera as pa
import numpy as np

In [2]:
valores_ausentes = ['**', '***', '****', '###!', '####', 'NULL']
df = pd.read_csv('ocorrencia.csv', sep = ',', parse_dates = ['ocorrencia_dia'], dayfirst = True, na_values = valores_ausentes)
df.head()

,codigo_ocorrencia,codigo_ocorrencia2,ocorrencia_classificacao,ocorrencia_cidade,ocorrencia_uf,ocorrencia_aerodromo,ocorrencia_dia,ocorrencia_hora,total_recomendacoes
0,52242,52242,INCIDENTE,PORTO ALEGRE,RS,SBPA,2012-01-05,20:27:00,0
1,45331,45331,ACIDENTE,GUARULHOS,SP,SBGR,2012-01-06,13:44:00,3
2,45333,45333,ACIDENTE,VIAMÃO,RS,NaN,2012-01-06,13:00:00,0
3,45401,45401,ACIDENTE,SÃO SEBASTIÃO,SP,NaN,2012-01-06,17:00:00,0
4,45407,45407,ACIDENTE,SÃO SEPÉ,RS,NaN,2012-01-06,16:30:00,0

In [3]:
schema = pa.DataFrameSchema(
        columns = {
            'codigo_ocorrencia': pa.Column(pa.Int),
            'codigo_ocorrencia2': pa.Column(pa.Int),
            'ocorrencia_classificacao': pa.Column(pa.String),
            'ocorrencia_cidade': pa.Column(pa.String),
            'ocorrencia_uf': pa.Column(pa.String, pa.Check.str_length(2,2), nullable = True),
            'ocorrencia_aerodromo': pa.Column(pa.String, nullable = True),
            'ocorrencia_dia': pa.Column(pa.DateTime),
            'ocorrencia_hora': pa.Column(pa.String, pa.Check.str_matches(r'^([0-1]?[0-9]|[2][0-3]):([0-5][0-9])(:[0-5][0-9])?$'), nullable = True),
            'total_recomendacoes': pa.Column(pa.Int)           
        }

)

In [4]:
schema.validate(df)

,codigo_ocorrencia,codigo_ocorrencia2,ocorrencia_classificacao,ocorrencia_cidade,ocorrencia_uf,ocorrencia_aerodromo,ocorrencia_dia,ocorrencia_hora,total_recomendacoes
0,52242,52242,INCIDENTE,PORTO ALEGRE,RS,SBPA,2012-01-05,20:27:00,0
1,45331,45331,ACIDENTE,GUARULHOS,SP,SBGR,2012-01-06,13:44:00,3
2,45333,45333,ACIDENTE,VIAMÃO,RS,NaN,2012-01-06,13:00:00,0
3,45401,45401,ACIDENTE,SÃO SEBASTIÃO,SP,NaN,2012-01-06,17:00:00,0
4,45407,45407,ACIDENTE,SÃO SEPÉ,RS,NaN,2012-01-06,16:30:00,0
...,...,...,...,...,...,...,...,...,...
5145,80458,80458,ACIDENTE,JATAÍ,GO,NaN,2021-12-30,20:30:00,0
5146,80452,80452,ACIDENTE,MARACAÍ,SP,NaN,2021-12-31,09:30:00,0
5147,80457,80457,INCIDENTE GRAVE,NOVO HAMBURGO,RS,SSNH,2021-12-31,11:59:00,0
5148,80460,80460,INCIDENTE,CURITIBA,PR,SBBI,2021-12-31,15:12:00,0
5149,80467,80467,INCIDENTE,PETROLINA,PE,SBPL,2021-12-31,20:30:00,0

In [5]:
df.dtypes

codigo_ocorrencia                    int64
codigo_ocorrencia2                   int64
ocorrencia_classificacao            object
ocorrencia_cidade                   object
ocorrencia_uf                       object
ocorrencia_aerodromo                object
ocorrencia_dia              datetime64[ns]
ocorrencia_hora                     object
total_recomendacoes                  int64
dtype: object

In [6]:
df.loc[1]

codigo_ocorrencia                         45331
codigo_ocorrencia2                        45331
ocorrencia_classificacao               ACIDENTE
ocorrencia_cidade                     GUARULHOS
ocorrencia_uf                                SP
ocorrencia_aerodromo                       SBGR
ocorrencia_dia              2012-01-06 00:00:00
ocorrencia_hora                        13:44:00
total_recomendacoes                           3
Name: 1, dtype: object

In [7]:
df.iloc[1]

codigo_ocorrencia                         45331
codigo_ocorrencia2                        45331
ocorrencia_classificacao               ACIDENTE
ocorrencia_cidade                     GUARULHOS
ocorrencia_uf                                SP
ocorrencia_aerodromo                       SBGR
ocorrencia_dia              2012-01-06 00:00:00
ocorrencia_hora                        13:44:00
total_recomendacoes                           3
Name: 1, dtype: object

In [8]:
df.iloc[-1]

codigo_ocorrencia                         80467
codigo_ocorrencia2                        80467
ocorrencia_classificacao              INCIDENTE
ocorrencia_cidade                     PETROLINA
ocorrencia_uf                                PE
ocorrencia_aerodromo                       SBPL
ocorrencia_dia              2021-12-31 00:00:00
ocorrencia_hora                        20:30:00
total_recomendacoes                           0
Name: 5149, dtype: object

In [9]:
df.iloc[10:15]

,codigo_ocorrencia,codigo_ocorrencia2,ocorrencia_classificacao,ocorrencia_cidade,ocorrencia_uf,ocorrencia_aerodromo,ocorrencia_dia,ocorrencia_hora,total_recomendacoes
10,45332,45332,ACIDENTE,VIAMÃO,RS,NaN,2012-01-09,13:30:00,0
11,52245,52245,INCIDENTE,PORTO ALEGRE,RS,SBPA,2012-01-09,13:36:00,0
12,45396,45396,INCIDENTE GRAVE,MARABÁ,PA,SBMA,2012-01-11,11:21:00,0
13,45408,45408,ACIDENTE,ELDORADO,SP,NaN,2012-01-11,13:45:00,1
14,45447,45447,INCIDENTE,RIO BRANCO,AC,NaN,2012-01-13,18:15:00,0

In [10]:
df.loc[10:15]

,codigo_ocorrencia,codigo_ocorrencia2,ocorrencia_classificacao,ocorrencia_cidade,ocorrencia_uf,ocorrencia_aerodromo,ocorrencia_dia,ocorrencia_hora,total_recomendacoes
10,45332,45332,ACIDENTE,VIAMÃO,RS,NaN,2012-01-09,13:30:00,0
11,52245,52245,INCIDENTE,PORTO ALEGRE,RS,SBPA,2012-01-09,13:36:00,0
12,45396,45396,INCIDENTE GRAVE,MARABÁ,PA,SBMA,2012-01-11,11:21:00,0
13,45408,45408,ACIDENTE,ELDORADO,SP,NaN,2012-01-11,13:45:00,1
14,45447,45447,INCIDENTE,RIO BRANCO,AC,NaN,2012-01-13,18:15:00,0
15,45409,45409,ACIDENTE,CÁCERES,MT,NaN,2012-01-14,10:00:00,0

In [11]:
df.loc[:,'ocorrencia_uf']

0       RS
1       SP
2       RS
3       SP
4       RS
        ..
5145    GO
5146    SP
5147    RS
5148    PR
5149    PE
Name: ocorrencia_uf, Length: 5150, dtype: object

In [12]:
df['ocorrencia_uf']

0       RS
1       SP
2       RS
3       SP
4       RS
        ..
5145    GO
5146    SP
5147    RS
5148    PR
5149    PE
Name: ocorrencia_uf, Length: 5150, dtype: object

In [13]:
df.isna().sum()

codigo_ocorrencia              0
codigo_ocorrencia2             0
ocorrencia_classificacao       0
ocorrencia_cidade              0
ocorrencia_uf                  2
ocorrencia_aerodromo        1897
ocorrencia_dia                 0
ocorrencia_hora                1
total_recomendacoes            0
dtype: int64

In [14]:
df.isnull().sum()

codigo_ocorrencia              0
codigo_ocorrencia2             0
ocorrencia_classificacao       0
ocorrencia_cidade              0
ocorrencia_uf                  2
ocorrencia_aerodromo        1897
ocorrencia_dia                 0
ocorrencia_hora                1
total_recomendacoes            0
dtype: int64

In [15]:
filtro = df.ocorrencia_uf.isnull()
df.loc[filtro]

,codigo_ocorrencia,codigo_ocorrencia2,ocorrencia_classificacao,ocorrencia_cidade,ocorrencia_uf,ocorrencia_aerodromo,ocorrencia_dia,ocorrencia_hora,total_recomendacoes
1099,49474,49474,ACIDENTE,ÁGUAS INTERNACIONAIS,NaN,NaN,2013-09-02,02:54:00,0
4718,79956,79956,ACIDENTE,NÃO IDENTIFICADA,NaN,NaN,2021-02-26,11:00:00,0

In [16]:
filtro = df.ocorrencia_aerodromo.isnull()
df.loc[filtro]

,codigo_ocorrencia,codigo_ocorrencia2,ocorrencia_classificacao,ocorrencia_cidade,ocorrencia_uf,ocorrencia_aerodromo,ocorrencia_dia,ocorrencia_hora,total_recomendacoes
2,45333,45333,ACIDENTE,VIAMÃO,RS,NaN,2012-01-06,13:00:00,0
3,45401,45401,ACIDENTE,SÃO SEBASTIÃO,SP,NaN,2012-01-06,17:00:00,0
4,45407,45407,ACIDENTE,SÃO SEPÉ,RS,NaN,2012-01-06,16:30:00,0
5,52243,52243,INCIDENTE,UBATUBA,SP,NaN,2012-01-06,14:30:00,0
8,45391,45391,ACIDENTE,CONCEIÇÃO DAS ALAGOAS,MG,NaN,2012-01-08,16:00:00,0
...,...,...,...,...,...,...,...,...,...
5134,80446,80446,ACIDENTE,JACAREACANGA,PA,NaN,2021-12-20,17:10:00,0
5138,80450,80450,ACIDENTE,DOURADOS,MS,NaN,2021-12-28,10:30:00,0
5142,80455,80455,INCIDENTE GRAVE,SANTA RITA,PB,NaN,2021-12-29,18:50:00,0
5145,80458,80458,ACIDENTE,JATAÍ,GO,NaN,2021-12-30,20:30:00,0
5146,80452,80452,ACIDENTE,MARACAÍ,SP,NaN,2021-12-31,09:30:00,0

In [17]:
filtro = df.ocorrencia_hora.isnull()
df.loc[filtro]

,codigo_ocorrencia,codigo_ocorrencia2,ocorrencia_classificacao,ocorrencia_cidade,ocorrencia_uf,ocorrencia_aerodromo,ocorrencia_dia,ocorrencia_hora,total_recomendacoes
2972,78823,78823,INCIDENTE,CORUMBÁ,MS,NaN,2017-07-09,NaN,0

In [18]:
df.count()

codigo_ocorrencia           5150
codigo_ocorrencia2          5150
ocorrencia_classificacao    5150
ocorrencia_cidade           5150
ocorrencia_uf               5148
ocorrencia_aerodromo        3253
ocorrencia_dia              5150
ocorrencia_hora             5149
total_recomendacoes         5150
dtype: int64

In [19]:
#Ocorrências com mais de 10 recomendações
filtro = df.total_recomendacoes > 10
df.loc[filtro]

,codigo_ocorrencia,codigo_ocorrencia2,ocorrencia_classificacao,ocorrencia_cidade,ocorrencia_uf,ocorrencia_aerodromo,ocorrencia_dia,ocorrencia_hora,total_recomendacoes
844,47938,47938,INCIDENTE,BRASÍLIA,DF,SBBR,2013-04-13,18:00:00,11
1669,52265,52265,ACIDENTE,SANTOS,SP,NaN,2014-08-13,13:03:00,13
2802,66432,66432,INCIDENTE GRAVE,VITÓRIA,ES,NaN,2017-02-21,11:47:00,12

In [20]:
#Ocorrências com mais de 10 recomendações
filtro = df.total_recomendacoes > 10
df.loc[filtro,['ocorrencia_cidade', 'total_recomendacoes']]

     ocorrencia_cidade  total_recomendacoes
844           BRASÍLIA                   11
1669            SANTOS                   13
2802           VITÓRIA                   12

In [21]:
#Ocorrências cuja classificação é igual a INCIDENTE GRAVE
filtro = df.ocorrencia_classificacao == 'INCIDENTE GRAVE'
df.loc[filtro]

,codigo_ocorrencia,codigo_ocorrencia2,ocorrencia_classificacao,ocorrencia_cidade,ocorrencia_uf,ocorrencia_aerodromo,ocorrencia_dia,ocorrencia_hora,total_recomendacoes
6,50713,50713,INCIDENTE GRAVE,CAMPINAS,SP,SDAI,2012-01-07,18:15:00,0
12,45396,45396,INCIDENTE GRAVE,MARABÁ,PA,SBMA,2012-01-11,11:21:00,0
18,50714,50714,INCIDENTE GRAVE,CAMOCIM,CE,SNWC,2012-01-17,18:25:00,0
19,45399,45399,INCIDENTE GRAVE,MUANÁ,PA,NaN,2012-01-18,17:35:00,0
24,45582,45582,INCIDENTE GRAVE,RONDONÓPOLIS,MT,SWRD,2012-01-20,17:00:00,0
...,...,...,...,...,...,...,...,...,...
5122,80427,80427,INCIDENTE GRAVE,NOVA BANDEIRANTES,MT,NaN,2021-12-12,17:20:00,0
5129,80448,80448,INCIDENTE GRAVE,FORMOSO DO ARAGUAIA,TO,NaN,2021-12-18,19:00:00,0
5141,80454,80454,INCIDENTE GRAVE,ARAÇATUBA,SP,SBAU,2021-12-29,21:35:00,0
5142,80455,80455,INCIDENTE GRAVE,SANTA RITA,PB,NaN,2021-12-29,18:50:00,0
5147,80457,80457,INCIDENTE GRAVE,NOVO HAMBURGO,RS,SSNH,2021-12-31,11:59:00,0

In [22]:
#Ocorrências cuja classificação é igual a INCIDENTE GRAVE e o estado é São Paulo
filtro1 = df.ocorrencia_classificacao == 'INCIDENTE GRAVE'
filtro2 = df.ocorrencia_uf == 'SP'
df.loc[filtro1 & filtro2]

,codigo_ocorrencia,codigo_ocorrencia2,ocorrencia_classificacao,ocorrencia_cidade,ocorrencia_uf,ocorrencia_aerodromo,ocorrencia_dia,ocorrencia_hora,total_recomendacoes
6,50713,50713,INCIDENTE GRAVE,CAMPINAS,SP,SDAI,2012-01-07,18:15:00,0
78,45598,45598,INCIDENTE GRAVE,BRAGANÇA PAULISTA,SP,SBBP,2012-02-20,14:10:00,0
86,45653,45653,INCIDENTE GRAVE,GUARULHOS,SP,SBGR,2012-02-24,20:04:00,0
91,45599,45599,INCIDENTE GRAVE,BRAGANÇA PAULISTA,SP,SBBP,2012-02-27,19:15:00,0
140,45651,45651,INCIDENTE GRAVE,ITU,SP,NaN,2012-03-24,20:45:00,1
...,...,...,...,...,...,...,...,...,...
4939,80200,80200,INCIDENTE GRAVE,BRAGANÇA PAULISTA,SP,SDVH,2021-07-25,12:25:00,0
4965,80238,80238,INCIDENTE GRAVE,VOTUPORANGA,SP,SDVG,2021-08-11,19:09:00,0
4988,80265,80265,INCIDENTE GRAVE,SÃO PAULO,SP,SBMT,2021-08-31,16:50:00,0
5081,80382,80382,INCIDENTE GRAVE,PIRACICABA,SP,SDPW,2021-11-16,20:50:00,0
5141,80454,80454,INCIDENTE GRAVE,ARAÇATUBA,SP,SBAU,2021-12-29,21:35:00,0

In [23]:
#Ocorrências cuja classificação é igual a INCIDENTE GRAVE OU o estado é São Paulo
filtro1 = df.ocorrencia_classificacao == 'INCIDENTE GRAVE'
filtro2 = df.ocorrencia_uf == 'SP'
df.loc[filtro1 | filtro2]

,codigo_ocorrencia,codigo_ocorrencia2,ocorrencia_classificacao,ocorrencia_cidade,ocorrencia_uf,ocorrencia_aerodromo,ocorrencia_dia,ocorrencia_hora,total_recomendacoes
1,45331,45331,ACIDENTE,GUARULHOS,SP,SBGR,2012-01-06,13:44:00,3
3,45401,45401,ACIDENTE,SÃO SEBASTIÃO,SP,NaN,2012-01-06,17:00:00,0
5,52243,52243,INCIDENTE,UBATUBA,SP,NaN,2012-01-06,14:30:00,0
6,50713,50713,INCIDENTE GRAVE,CAMPINAS,SP,SDAI,2012-01-07,18:15:00,0
12,45396,45396,INCIDENTE GRAVE,MARABÁ,PA,SBMA,2012-01-11,11:21:00,0
...,...,...,...,...,...,...,...,...,...
5141,80454,80454,INCIDENTE GRAVE,ARAÇATUBA,SP,SBAU,2021-12-29,21:35:00,0
5142,80455,80455,INCIDENTE GRAVE,SANTA RITA,PB,NaN,2021-12-29,18:50:00,0
5144,80456,80456,INCIDENTE,SÃO PAULO,SP,SBSP,2021-12-30,13:15:00,0
5146,80452,80452,ACIDENTE,MARACAÍ,SP,NaN,2021-12-31,09:30:00,0
5147,80457,80457,INCIDENTE GRAVE,NOVO HAMBURGO,RS,SSNH,2021-12-31,11:59:00,0

In [24]:
#Ocorrências cuja classificação é igual a INCIDENTE GRAVE OU INCIDENTE e o estado é São Paulo
filtro1 = (df.ocorrencia_classificacao == 'INCIDENTE GRAVE') | (df.ocorrencia_classificacao == 'INCIDENTE')
filtro2 = df.ocorrencia_uf == 'SP'
df.loc[filtro1 & filtro2]

,codigo_ocorrencia,codigo_ocorrencia2,ocorrencia_classificacao,ocorrencia_cidade,ocorrencia_uf,ocorrencia_aerodromo,ocorrencia_dia,ocorrencia_hora,total_recomendacoes
5,52243,52243,INCIDENTE,UBATUBA,SP,NaN,2012-01-06,14:30:00,0
6,50713,50713,INCIDENTE GRAVE,CAMPINAS,SP,SDAI,2012-01-07,18:15:00,0
28,52248,52248,INCIDENTE,SÃO PAULO,SP,SBMT,2012-01-21,11:15:00,0
35,52054,52054,INCIDENTE,SÃO PAULO,SP,SBMT,2012-01-25,23:00:00,0
36,52055,52055,INCIDENTE,RIBEIRÃO PRETO,SP,NaN,2012-01-25,09:30:00,0
...,...,...,...,...,...,...,...,...,...
5117,80425,80425,INCIDENTE,SÃO PAULO,SP,SBSP,2021-12-09,20:30:00,0
5126,80431,80431,INCIDENTE,SANTOS,SP,SBST,2021-12-15,12:30:00,0
5140,80453,80453,INCIDENTE,CAMPINAS,SP,SBKP,2021-12-29,09:00:00,0
5141,80454,80454,INCIDENTE GRAVE,ARAÇATUBA,SP,SBAU,2021-12-29,21:35:00,0
5144,80456,80456,INCIDENTE,SÃO PAULO,SP,SBSP,2021-12-30,13:15:00,0

In [25]:
#Ocorrências cuja classificação é igual a INCIDENTE GRAVE OU INCIDENTE e o estado é São Paulo
filtro1 = df.ocorrencia_classificacao.isin(['INCIDENTE GRAVE', 'INCIDENTE'])
filtro2 = df.ocorrencia_uf == 'SP'
df.loc[filtro1 & filtro2]

,codigo_ocorrencia,codigo_ocorrencia2,ocorrencia_classificacao,ocorrencia_cidade,ocorrencia_uf,ocorrencia_aerodromo,ocorrencia_dia,ocorrencia_hora,total_recomendacoes
5,52243,52243,INCIDENTE,UBATUBA,SP,NaN,2012-01-06,14:30:00,0
6,50713,50713,INCIDENTE GRAVE,CAMPINAS,SP,SDAI,2012-01-07,18:15:00,0
28,52248,52248,INCIDENTE,SÃO PAULO,SP,SBMT,2012-01-21,11:15:00,0
35,52054,52054,INCIDENTE,SÃO PAULO,SP,SBMT,2012-01-25,23:00:00,0
36,52055,52055,INCIDENTE,RIBEIRÃO PRETO,SP,NaN,2012-01-25,09:30:00,0
...,...,...,...,...,...,...,...,...,...
5117,80425,80425,INCIDENTE,SÃO PAULO,SP,SBSP,2021-12-09,20:30:00,0
5126,80431,80431,INCIDENTE,SANTOS,SP,SBST,2021-12-15,12:30:00,0
5140,80453,80453,INCIDENTE,CAMPINAS,SP,SBKP,2021-12-29,09:00:00,0
5141,80454,80454,INCIDENTE GRAVE,ARAÇATUBA,SP,SBAU,2021-12-29,21:35:00,0
5144,80456,80456,INCIDENTE,SÃO PAULO,SP,SBSP,2021-12-30,13:15:00,0

In [26]:
#Ocorrências cuja cidade começa com a letra 'C'
filtro = df.ocorrencia_cidade.str[0] == 'C'
df.loc[filtro]

,codigo_ocorrencia,codigo_ocorrencia2,ocorrencia_classificacao,ocorrencia_cidade,ocorrencia_uf,ocorrencia_aerodromo,ocorrencia_dia,ocorrencia_hora,total_recomendacoes
6,50713,50713,INCIDENTE GRAVE,CAMPINAS,SP,SDAI,2012-01-07,18:15:00,0
8,45391,45391,ACIDENTE,CONCEIÇÃO DAS ALAGOAS,MG,NaN,2012-01-08,16:00:00,0
15,45409,45409,ACIDENTE,CÁCERES,MT,NaN,2012-01-14,10:00:00,0
18,50714,50714,INCIDENTE GRAVE,CAMOCIM,CE,SNWC,2012-01-17,18:25:00,0
22,45390,45390,ACIDENTE,CACHOEIRA DOURADA,GO,NaN,2012-01-20,21:00:00,0
...,...,...,...,...,...,...,...,...,...
5125,80434,80434,ACIDENTE,CARACOL,MS,NaN,2021-12-14,21:35:00,0
5127,80447,80447,INCIDENTE,CONFINS,MG,SBCF,2021-12-15,17:10:00,0
5133,80445,80445,ACIDENTE,CHUPINGUAIA,RO,NaN,2021-12-20,12:05:00,0
5140,80453,80453,INCIDENTE,CAMPINAS,SP,SBKP,2021-12-29,09:00:00,0
5148,80460,80460,INCIDENTE,CURITIBA,PR,SBBI,2021-12-31,15:12:00,0

In [27]:
#Ocorrências cuja cidade terminam com a letra 'A'
filtro = df.ocorrencia_cidade.str[-1] == 'A'
df.loc[filtro]

,codigo_ocorrencia,codigo_ocorrencia2,ocorrencia_classificacao,ocorrencia_cidade,ocorrencia_uf,ocorrencia_aerodromo,ocorrencia_dia,ocorrencia_hora,total_recomendacoes
5,52243,52243,INCIDENTE,UBATUBA,SP,NaN,2012-01-06,14:30:00,0
9,52244,52244,INCIDENTE,UBERLÂNDIA,MG,SBUL,2012-01-08,22:13:00,0
17,52246,52246,INCIDENTE,BRASÍLIA,DF,SBBR,2012-01-16,16:47:00,0
21,45392,45392,ACIDENTE,BRASÍLIA,DF,NaN,2012-01-19,21:30:00,2
22,45390,45390,ACIDENTE,CACHOEIRA DOURADA,GO,NaN,2012-01-20,21:00:00,0
...,...,...,...,...,...,...,...,...,...
5135,80465,80465,INCIDENTE,VITÓRIA,ES,SBVT,2021-12-21,22:25:00,0
5141,80454,80454,INCIDENTE GRAVE,ARAÇATUBA,SP,SBAU,2021-12-29,21:35:00,0
5142,80455,80455,INCIDENTE GRAVE,SANTA RITA,PB,NaN,2021-12-29,18:50:00,0
5148,80460,80460,INCIDENTE,CURITIBA,PR,SBBI,2021-12-31,15:12:00,0
5149,80467,80467,INCIDENTE,PETROLINA,PE,SBPL,2021-12-31,20:30:00,0

In [28]:
#Ocorrências cuja cidade terminam com os caracteres 'MA'
filtro = df.ocorrencia_cidade.str[-2:] == 'MA'
df.loc[filtro]

,codigo_ocorrencia,codigo_ocorrencia2,ocorrencia_classificacao,ocorrencia_cidade,ocorrencia_uf,ocorrencia_aerodromo,ocorrencia_dia,ocorrencia_hora,total_recomendacoes
249,45939,45939,ACIDENTE,UMUARAMA,PR,NaN,2012-05-30,19:00:00,0
273,46180,46180,ACIDENTE,AURIFLAMA,SP,NaN,2012-06-16,19:30:00,0
971,49113,49113,INCIDENTE GRAVE,NOVA LIMA,MG,NaN,2013-06-15,12:00:00,4
974,48799,48799,ACIDENTE,CANUTAMA,AM,NaN,2013-06-18,21:30:00,0
1518,80059,80059,INCIDENTE,IVINHEMA,MS,NaN,2014-04-27,11:30:00,0
1529,51347,51347,INCIDENTE,DIADEMA,SP,NaN,2014-05-04,16:00:00,0
1729,52340,52340,ACIDENTE,FAMA,MG,NaN,2014-09-20,15:00:00,1
1839,52832,52832,ACIDENTE,BURITAMA,SP,NaN,2014-12-14,23:40:00,0
1869,52979,52979,ACIDENTE,IVINHEMA,MS,NaN,2015-01-02,14:50:00,0
1912,52984,52984,ACIDENTE,NOVA LIMA,MG,SJLY,2015-02-01,15:10:00,0
1964,53596,53596,INCIDENTE,ITAPEMA,SC,NaN,2015-03-10,21:35:00,0
2029,53223,53223,ACIDENTE,PINDORAMA,SP,NaN,2015-04-22,12:45:00,0
2043,53265,53265,ACIDENTE,PACARAIMA,RR,SDMM,2015-05-05,16:05:00,2
2061,53271,53271,INCIDENTE GRAVE,UMUARAMA,PR,NaN,2015-05-17,17:00:00,0
2554,65414,65414,INCIDENTE GRAVE,NOVA LIMA,MG,SJLY,2016-07-08,19:50:00,1
2597,65633,65633,INCIDENTE GRAVE,NOVA LIMA,MG,NaN,2016-08-31,17:40:00,0
2753,66265,66265,ACIDENTE,BURITAMA,SP,NaN,2017-01-13,16:00:00,0
3102,77371,77371,ACIDENTE,CANUTAMA,AM,SDKH,2017-11-02,19:30:00,1
3184,77612,77612,ACIDENTE,ITAPEMA,SC,NaN,2018-01-06,10:30:00,0
3445,78080,78080,ACIDENTE,ITAPEMA,SC,NaN,2018-07-28,14:20:00,0
3857,78867,78867,INCIDENTE,IRACEMA,RR,NaN,2019-07-06,00:00:00,0
3941,78923,78923,INCIDENTE GRAVE,CANUTAMA,AM,NaN,2019-09-03,14:00:00,0
3951,78782,78782,ACIDENTE,IVINHEMA,MS,NaN,2019-09-08,17:45:00,0
4275,79282,79282,ACIDENTE,ITURAMA,MG,NaN,2020-04-11,12:20:00,0
4310,79338,79338,INCIDENTE,IVINHEMA,MS,NaN,2020-05-15,09:40:00,0
4343,79400,79400,INCIDENTE,IBIRAMA,SC,NaN,2020-06-09,14:00:00,0
4623,79823,79823,ACIDENTE,IRACEMA,RR,NaN,2021-01-05,20:07:00,0
4641,79830,79830,INCIDENTE,NOVA LIMA,MG,SJLY,2021-01-14,09:27:00,0
4724,79943,79943,INCIDENTE,IBOTIRAMA,BA,SNIT,2021-03-03,11:30:00,0
4952,80227,80227,ACIDENTE,UMUARAMA,PR,NaN,2021-08-02,14:30:00,0
4954,80252,80252,ACIDENTE,IRACEMA,RR,NaN,2021-08-04,11:45:00,0

In [29]:
#Ocorrências cuja cidade contém os caracteres 'MA'
filtro = df.ocorrencia_cidade.str.contains('MA')
df.loc[filtro]

,codigo_ocorrencia,codigo_ocorrencia2,ocorrencia_classificacao,ocorrencia_cidade,ocorrencia_uf,ocorrencia_aerodromo,ocorrencia_dia,ocorrencia_hora,total_recomendacoes
12,45396,45396,INCIDENTE GRAVE,MARABÁ,PA,SBMA,2012-01-11,11:21:00,0
16,45693,45693,INCIDENTE,MACAÉ,RJ,NaN,2012-01-14,10:30:00,0
45,45682,45682,INCIDENTE,MACAÉ,RJ,NaN,2012-02-01,13:50:00,0
59,45580,45580,INCIDENTE GRAVE,MACAÉ,RJ,NaN,2012-02-07,14:50:00,4
79,45715,45715,INCIDENTE,MANAUS,AM,SWFN,2012-02-20,09:10:00,0
...,...,...,...,...,...,...,...,...,...
5121,80428,80428,ACIDENTE,SANTA VITÓRIA DO PALMAR,RS,NaN,2021-12-11,19:40:00,0
5136,80461,80461,INCIDENTE,MARINGÁ,PR,SBMG,2021-12-24,03:30:00,0
5139,80463,80463,INCIDENTE,MARINGÁ,PR,SBMG,2021-12-28,16:11:00,0
5143,80451,80451,INCIDENTE,MANAUS,AM,SBEG,2021-12-30,14:41:00,0
5146,80452,80452,ACIDENTE,MARACAÍ,SP,NaN,2021-12-31,09:30:00,0

In [30]:
#Ocorrências cuja cidade contém os caracteres 'MA' OU 'AL'
filtro = df.ocorrencia_cidade.str.contains('MA|AL')
df.loc[filtro]

,codigo_ocorrencia,codigo_ocorrencia2,ocorrencia_classificacao,ocorrencia_cidade,ocorrencia_uf,ocorrencia_aerodromo,ocorrencia_dia,ocorrencia_hora,total_recomendacoes
0,52242,52242,INCIDENTE,PORTO ALEGRE,RS,SBPA,2012-01-05,20:27:00,0
8,45391,45391,ACIDENTE,CONCEIÇÃO DAS ALAGOAS,MG,NaN,2012-01-08,16:00:00,0
11,52245,52245,INCIDENTE,PORTO ALEGRE,RS,SBPA,2012-01-09,13:36:00,0
12,45396,45396,INCIDENTE GRAVE,MARABÁ,PA,SBMA,2012-01-11,11:21:00,0
16,45693,45693,INCIDENTE,MACAÉ,RJ,NaN,2012-01-14,10:30:00,0
...,...,...,...,...,...,...,...,...,...
5136,80461,80461,INCIDENTE,MARINGÁ,PR,SBMG,2021-12-24,03:30:00,0
5137,80468,80468,INCIDENTE,SALVADOR,BA,SBSV,2021-12-26,16:56:00,0
5139,80463,80463,INCIDENTE,MARINGÁ,PR,SBMG,2021-12-28,16:11:00,0
5143,80451,80451,INCIDENTE,MANAUS,AM,SBEG,2021-12-30,14:41:00,0
5146,80452,80452,ACIDENTE,MARACAÍ,SP,NaN,2021-12-31,09:30:00,0

In [31]:
#Ocorrências do ano de 2015
filtro = df.ocorrencia_dia.dt.year == 2015
df.loc[filtro]

,codigo_ocorrencia,codigo_ocorrencia2,ocorrencia_classificacao,ocorrencia_cidade,ocorrencia_uf,ocorrencia_aerodromo,ocorrencia_dia,ocorrencia_hora,total_recomendacoes
1868,52992,52992,INCIDENTE GRAVE,SALVADOR,BA,SBSV,2015-01-01,11:40:00,3
1869,52979,52979,ACIDENTE,IVINHEMA,MS,NaN,2015-01-02,14:50:00,0
1870,53073,53073,INCIDENTE,TEFÉ,AM,SBTF,2015-01-02,16:28:00,0
1871,53074,53074,INCIDENTE,BELO HORIZONTE,MG,SBBH,2015-01-02,20:34:00,0
1872,52976,52976,ACIDENTE,TOLEDO,PR,SBTD,2015-01-04,22:04:00,6
...,...,...,...,...,...,...,...,...,...
2334,60632,60632,INCIDENTE GRAVE,ITABERÁ,SP,NaN,2015-12-24,14:00:00,0
2335,60600,60600,INCIDENTE,GUARULHOS,SP,SBGR,2015-12-25,19:00:00,0
2336,60642,60642,INCIDENTE,SÃO FRANCISCO DO SUL,SC,SSSS,2015-12-26,16:00:00,0
2337,60631,60631,ACIDENTE,MAÇAMBARÁ,RS,NaN,2015-12-28,19:00:00,2
2338,60649,60649,ACIDENTE,PORTO BELO,SC,SDEN,2015-12-31,14:00:00,0

In [32]:
#Ocorrências do ano de 2015 E mês 12
filtro1 = df.ocorrencia_dia.dt.year == 2015
filtro2 = df.ocorrencia_dia.dt.month == 12
df.loc[filtro1 & filtro2]

,codigo_ocorrencia,codigo_ocorrencia2,ocorrencia_classificacao,ocorrencia_cidade,ocorrencia_uf,ocorrencia_aerodromo,ocorrencia_dia,ocorrencia_hora,total_recomendacoes
2300,53573,53573,INCIDENTE,GUARULHOS,SP,SBGR,2015-12-01,02:48:00,0
2301,60601,60601,INCIDENTE,PALMAS,TO,SBPJ,2015-12-01,16:05:00,0
2302,53634,53634,INCIDENTE,PALMAS,TO,SBPJ,2015-12-02,17:45:00,0
2303,53636,53636,INCIDENTE,JUNDIAÍ,SP,SBJD,2015-12-02,17:42:00,0
2304,53575,53575,INCIDENTE,CAMPOS DOS GOYTACAZES,RJ,SBFS,2015-12-03,10:50:00,0
2305,60637,60637,INCIDENTE,BELO HORIZONTE,MG,SBBH,2015-12-03,16:47:00,0
2306,53625,53625,ACIDENTE,TRINDADE,GO,NaN,2015-12-06,13:10:00,3
2307,53626,53626,ACIDENTE,AMERICANA,SP,SDAI,2015-12-06,15:00:00,1
2308,53628,53628,ACIDENTE,AGUAÍ,SP,NaN,2015-12-08,14:30:00,1
2309,53629,53629,INCIDENTE GRAVE,JALES,SP,SDJL,2015-12-08,10:20:00,0
2310,53631,53631,INCIDENTE,CAMPINAS,SP,SBKP,2015-12-08,16:19:00,0
2311,60636,60636,INCIDENTE,CAXIAS DO SUL,RS,SBCX,2015-12-08,13:00:00,0
2312,53627,53627,INCIDENTE,TERESINA,PI,SBTE,2015-12-12,19:05:00,0
2313,60604,60604,INCIDENTE,GOIÂNIA,GO,SBGO,2015-12-12,14:34:00,0
2314,60611,60611,INCIDENTE,SÃO PAULO,SP,SBSP,2015-12-12,15:30:00,0
2315,60613,60613,ACIDENTE,JUSCIMEIRA,MT,SWMO,2015-12-12,08:31:00,0
2316,60629,60629,ACIDENTE,RIO GRANDE,RS,NaN,2015-12-12,10:40:00,0
2317,53630,53630,INCIDENTE,MARÍLIA,SP,SBML,2015-12-13,13:50:00,0
2318,60603,60603,INCIDENTE,LONDRINA,PR,SBLO,2015-12-13,17:46:00,0
2319,60612,60612,ACIDENTE,BENTO GONÇALVES,RS,SSBG,2015-12-13,20:30:00,0
2320,60783,60783,ACIDENTE,LAGES,SC,NaN,2015-12-13,14:00:00,3
2321,53639,53639,INCIDENTE,LOUVEIRA,SP,SDAM,2015-12-15,14:20:00,0
2322,60609,60609,INCIDENTE GRAVE,ARAGUAÍNA,TO,SWGN,2015-12-15,13:00:00,0
2323,60616,60616,ACIDENTE,PALOTINA,PR,NaN,2015-12-15,20:30:00,0
2324,60620,60620,ACIDENTE,RIO DE JANEIRO,RJ,SBJR,2015-12-15,16:50:00,4
2325,60645,60645,ACIDENTE,SERTÃOZINHO,SP,NaN,2015-12-15,13:00:00,0
2326,60608,60608,INCIDENTE,BELO HORIZONTE,MG,SBPR,2015-12-16,10:38:00,0
2327,60625,60625,ACIDENTE,ITÁPOLIS,SP,SDIO,2015-12-17,21:30:00,1
2328,60605,60605,INCIDENTE,UBERLÂNDIA,MG,SBUL,2015-12-18,10:25:00,0
2329,60610,60610,INCIDENTE,JUNDIAÍ,SP,SBJD,2015-12-18,18:45:00,0
2330,60602,60602,INCIDENTE,RIBEIRÃO PRETO,SP,SBRP,2015-12-22,06:27:00,0
2331,60615,60615,INCIDENTE,SÃO PAULO,SP,SBMT,2015-12-22,13:07:00,0
2332,60640,60640,INCIDENTE,CASCAVEL,PR,SBCA,2015-12-23,13:20:00,0
2333,60641,60641,INCIDENTE,BELO HORIZONTE,MG,SBBH,2015-12-23,15:53:00,0
2334,60632,60632,INCIDENTE GRAVE,ITABERÁ,SP,NaN,2015-12-24,14:00:00,0
2335,60600,60600,INCIDENTE,GUARULHOS,SP,SBGR,2015-12-25,19:00:00,0
2336,60642,60642,INCIDENTE,SÃO FRANCISCO DO SUL,SC,SSSS,2015-12-26,16:00:00,0
2337,60631,60631,ACIDENTE,MAÇAMBARÁ,RS,NaN,2015-12-28,19:00:00,2
2338,60649,60649,ACIDENTE,PORTO BELO,SC,SDEN,2015-12-31,14:00:00,0

In [33]:
#Ocorrências do ano de 2015 E mês 12
filtro = (df.ocorrencia_dia.dt.year == 2015) & (df.ocorrencia_dia.dt.month == 12)
df.loc[filtro]

,codigo_ocorrencia,codigo_ocorrencia2,ocorrencia_classificacao,ocorrencia_cidade,ocorrencia_uf,ocorrencia_aerodromo,ocorrencia_dia,ocorrencia_hora,total_recomendacoes
2300,53573,53573,INCIDENTE,GUARULHOS,SP,SBGR,2015-12-01,02:48:00,0
2301,60601,60601,INCIDENTE,PALMAS,TO,SBPJ,2015-12-01,16:05:00,0
2302,53634,53634,INCIDENTE,PALMAS,TO,SBPJ,2015-12-02,17:45:00,0
2303,53636,53636,INCIDENTE,JUNDIAÍ,SP,SBJD,2015-12-02,17:42:00,0
2304,53575,53575,INCIDENTE,CAMPOS DOS GOYTACAZES,RJ,SBFS,2015-12-03,10:50:00,0
2305,60637,60637,INCIDENTE,BELO HORIZONTE,MG,SBBH,2015-12-03,16:47:00,0
2306,53625,53625,ACIDENTE,TRINDADE,GO,NaN,2015-12-06,13:10:00,3
2307,53626,53626,ACIDENTE,AMERICANA,SP,SDAI,2015-12-06,15:00:00,1
2308,53628,53628,ACIDENTE,AGUAÍ,SP,NaN,2015-12-08,14:30:00,1
2309,53629,53629,INCIDENTE GRAVE,JALES,SP,SDJL,2015-12-08,10:20:00,0
2310,53631,53631,INCIDENTE,CAMPINAS,SP,SBKP,2015-12-08,16:19:00,0
2311,60636,60636,INCIDENTE,CAXIAS DO SUL,RS,SBCX,2015-12-08,13:00:00,0
2312,53627,53627,INCIDENTE,TERESINA,PI,SBTE,2015-12-12,19:05:00,0
2313,60604,60604,INCIDENTE,GOIÂNIA,GO,SBGO,2015-12-12,14:34:00,0
2314,60611,60611,INCIDENTE,SÃO PAULO,SP,SBSP,2015-12-12,15:30:00,0
2315,60613,60613,ACIDENTE,JUSCIMEIRA,MT,SWMO,2015-12-12,08:31:00,0
2316,60629,60629,ACIDENTE,RIO GRANDE,RS,NaN,2015-12-12,10:40:00,0
2317,53630,53630,INCIDENTE,MARÍLIA,SP,SBML,2015-12-13,13:50:00,0
2318,60603,60603,INCIDENTE,LONDRINA,PR,SBLO,2015-12-13,17:46:00,0
2319,60612,60612,ACIDENTE,BENTO GONÇALVES,RS,SSBG,2015-12-13,20:30:00,0
2320,60783,60783,ACIDENTE,LAGES,SC,NaN,2015-12-13,14:00:00,3
2321,53639,53639,INCIDENTE,LOUVEIRA,SP,SDAM,2015-12-15,14:20:00,0
2322,60609,60609,INCIDENTE GRAVE,ARAGUAÍNA,TO,SWGN,2015-12-15,13:00:00,0
2323,60616,60616,ACIDENTE,PALOTINA,PR,NaN,2015-12-15,20:30:00,0
2324,60620,60620,ACIDENTE,RIO DE JANEIRO,RJ,SBJR,2015-12-15,16:50:00,4
2325,60645,60645,ACIDENTE,SERTÃOZINHO,SP,NaN,2015-12-15,13:00:00,0
2326,60608,60608,INCIDENTE,BELO HORIZONTE,MG,SBPR,2015-12-16,10:38:00,0
2327,60625,60625,ACIDENTE,ITÁPOLIS,SP,SDIO,2015-12-17,21:30:00,1
2328,60605,60605,INCIDENTE,UBERLÂNDIA,MG,SBUL,2015-12-18,10:25:00,0
2329,60610,60610,INCIDENTE,JUNDIAÍ,SP,SBJD,2015-12-18,18:45:00,0
2330,60602,60602,INCIDENTE,RIBEIRÃO PRETO,SP,SBRP,2015-12-22,06:27:00,0
2331,60615,60615,INCIDENTE,SÃO PAULO,SP,SBMT,2015-12-22,13:07:00,0
2332,60640,60640,INCIDENTE,CASCAVEL,PR,SBCA,2015-12-23,13:20:00,0
2333,60641,60641,INCIDENTE,BELO HORIZONTE,MG,SBBH,2015-12-23,15:53:00,0
2334,60632,60632,INCIDENTE GRAVE,ITABERÁ,SP,NaN,2015-12-24,14:00:00,0
2335,60600,60600,INCIDENTE,GUARULHOS,SP,SBGR,2015-12-25,19:00:00,0
2336,60642,60642,INCIDENTE,SÃO FRANCISCO DO SUL,SC,SSSS,2015-12-26,16:00:00,0
2337,60631,60631,ACIDENTE,MAÇAMBARÁ,RS,NaN,2015-12-28,19:00:00,2
2338,60649,60649,ACIDENTE,PORTO BELO,SC,SDEN,2015-12-31,14:00:00,0

In [34]:
#Ocorrências do ano de 2015 E mês 12 E dia 8
filtro1 = df.ocorrencia_dia.dt.year == 2015
filtro2 = df.ocorrencia_dia.dt.month == 12
filtro3 = df.ocorrencia_dia.dt.day == 8
df.loc[filtro1 & filtro2 & filtro3]

,codigo_ocorrencia,codigo_ocorrencia2,ocorrencia_classificacao,ocorrencia_cidade,ocorrencia_uf,ocorrencia_aerodromo,ocorrencia_dia,ocorrencia_hora,total_recomendacoes
2308,53628,53628,ACIDENTE,AGUAÍ,SP,NaN,2015-12-08,14:30:00,1
2309,53629,53629,INCIDENTE GRAVE,JALES,SP,SDJL,2015-12-08,10:20:00,0
2310,53631,53631,INCIDENTE,CAMPINAS,SP,SBKP,2015-12-08,16:19:00,0
2311,60636,60636,INCIDENTE,CAXIAS DO SUL,RS,SBCX,2015-12-08,13:00:00,0

In [35]:
#Ocorrências do ano de 2015 E mês 12 E dia 3 a 8
filtro1 = df.ocorrencia_dia.dt.year == 2015
filtro2 = df.ocorrencia_dia.dt.month == 12
filtro3 = (df.ocorrencia_dia.dt.day >= 3) & (df.ocorrencia_dia.dt.day <=8) 
df.loc[filtro1 & filtro2 & filtro3]

,codigo_ocorrencia,codigo_ocorrencia2,ocorrencia_classificacao,ocorrencia_cidade,ocorrencia_uf,ocorrencia_aerodromo,ocorrencia_dia,ocorrencia_hora,total_recomendacoes
2304,53575,53575,INCIDENTE,CAMPOS DOS GOYTACAZES,RJ,SBFS,2015-12-03,10:50:00,0
2305,60637,60637,INCIDENTE,BELO HORIZONTE,MG,SBBH,2015-12-03,16:47:00,0
2306,53625,53625,ACIDENTE,TRINDADE,GO,NaN,2015-12-06,13:10:00,3
2307,53626,53626,ACIDENTE,AMERICANA,SP,SDAI,2015-12-06,15:00:00,1
2308,53628,53628,ACIDENTE,AGUAÍ,SP,NaN,2015-12-08,14:30:00,1
2309,53629,53629,INCIDENTE GRAVE,JALES,SP,SDJL,2015-12-08,10:20:00,0
2310,53631,53631,INCIDENTE,CAMPINAS,SP,SBKP,2015-12-08,16:19:00,0
2311,60636,60636,INCIDENTE,CAXIAS DO SUL,RS,SBCX,2015-12-08,13:00:00,0

In [36]:
df['ocorrencia_dia_hora'] = pd.to_datetime(df.ocorrencia_dia.astype(str) + ' ' + df.ocorrencia_hora)
df.head()

,codigo_ocorrencia,codigo_ocorrencia2,ocorrencia_classificacao,ocorrencia_cidade,ocorrencia_uf,ocorrencia_aerodromo,ocorrencia_dia,ocorrencia_hora,total_recomendacoes,ocorrencia_dia_hora
0,52242,52242,INCIDENTE,PORTO ALEGRE,RS,SBPA,2012-01-05,20:27:00,0,2012-01-05 20:27:00
1,45331,45331,ACIDENTE,GUARULHOS,SP,SBGR,2012-01-06,13:44:00,3,2012-01-06 13:44:00
2,45333,45333,ACIDENTE,VIAMÃO,RS,NaN,2012-01-06,13:00:00,0,2012-01-06 13:00:00
3,45401,45401,ACIDENTE,SÃO SEBASTIÃO,SP,NaN,2012-01-06,17:00:00,0,2012-01-06 17:00:00
4,45407,45407,ACIDENTE,SÃO SEPÉ,RS,NaN,2012-01-06,16:30:00,0,2012-01-06 16:30:00

In [37]:
df.dtypes

codigo_ocorrencia                    int64
codigo_ocorrencia2                   int64
ocorrencia_classificacao            object
ocorrencia_cidade                   object
ocorrencia_uf                       object
ocorrencia_aerodromo                object
ocorrencia_dia              datetime64[ns]
ocorrencia_hora                     object
total_recomendacoes                  int64
ocorrencia_dia_hora         datetime64[ns]
dtype: object

In [38]:
#Ocorrências do ano de 2015 E mês 12 E dia 3 a 8
filtro1 = df.ocorrencia_dia_hora.dt.year == 2015
filtro2 = df.ocorrencia_dia_hora.dt.month == 12
filtro3 = (df.ocorrencia_dia_hora.dt.day >= 3) & (df.ocorrencia_dia_hora.dt.day <=8) 
df.loc[filtro1 & filtro2 & filtro3]

,codigo_ocorrencia,codigo_ocorrencia2,ocorrencia_classificacao,ocorrencia_cidade,ocorrencia_uf,ocorrencia_aerodromo,ocorrencia_dia,ocorrencia_hora,total_recomendacoes,ocorrencia_dia_hora
2304,53575,53575,INCIDENTE,CAMPOS DOS GOYTACAZES,RJ,SBFS,2015-12-03,10:50:00,0,2015-12-03 10:50:00
2305,60637,60637,INCIDENTE,BELO HORIZONTE,MG,SBBH,2015-12-03,16:47:00,0,2015-12-03 16:47:00
2306,53625,53625,ACIDENTE,TRINDADE,GO,NaN,2015-12-06,13:10:00,3,2015-12-06 13:10:00
2307,53626,53626,ACIDENTE,AMERICANA,SP,SDAI,2015-12-06,15:00:00,1,2015-12-06 15:00:00
2308,53628,53628,ACIDENTE,AGUAÍ,SP,NaN,2015-12-08,14:30:00,1,2015-12-08 14:30:00
2309,53629,53629,INCIDENTE GRAVE,JALES,SP,SDJL,2015-12-08,10:20:00,0,2015-12-08 10:20:00
2310,53631,53631,INCIDENTE,CAMPINAS,SP,SBKP,2015-12-08,16:19:00,0,2015-12-08 16:19:00
2311,60636,60636,INCIDENTE,CAXIAS DO SUL,RS,SBCX,2015-12-08,13:00:00,0,2015-12-08 13:00:00

In [39]:
#Ocorrências do ano de 2015 E mês 12 E dia 3 a 8 das 11 horas as 13 horas
filtro1 = df.ocorrencia_dia_hora >= '2015-12-03 11:00:00'
filtro2 = df.ocorrencia_dia_hora <= '2015-12-08 13:00:00'
df.loc[filtro1 & filtro2]

,codigo_ocorrencia,codigo_ocorrencia2,ocorrencia_classificacao,ocorrencia_cidade,ocorrencia_uf,ocorrencia_aerodromo,ocorrencia_dia,ocorrencia_hora,total_recomendacoes,ocorrencia_dia_hora
2305,60637,60637,INCIDENTE,BELO HORIZONTE,MG,SBBH,2015-12-03,16:47:00,0,2015-12-03 16:47:00
2306,53625,53625,ACIDENTE,TRINDADE,GO,NaN,2015-12-06,13:10:00,3,2015-12-06 13:10:00
2307,53626,53626,ACIDENTE,AMERICANA,SP,SDAI,2015-12-06,15:00:00,1,2015-12-06 15:00:00
2309,53629,53629,INCIDENTE GRAVE,JALES,SP,SDJL,2015-12-08,10:20:00,0,2015-12-08 10:20:00
2311,60636,60636,INCIDENTE,CAXIAS DO SUL,RS,SBCX,2015-12-08,13:00:00,0,2015-12-08 13:00:00

In [40]:
#Ocorrências do ano de 2015 E mês 12 E dia 3 a 8 das 11 horas as 14:30
filtro1 = df.ocorrencia_dia_hora >= '2015-12-03 11:00:00'
filtro2 = df.ocorrencia_dia_hora <= '2015-12-08 14:30:00'
df.loc[filtro1 & filtro2]

,codigo_ocorrencia,codigo_ocorrencia2,ocorrencia_classificacao,ocorrencia_cidade,ocorrencia_uf,ocorrencia_aerodromo,ocorrencia_dia,ocorrencia_hora,total_recomendacoes,ocorrencia_dia_hora
2305,60637,60637,INCIDENTE,BELO HORIZONTE,MG,SBBH,2015-12-03,16:47:00,0,2015-12-03 16:47:00
2306,53625,53625,ACIDENTE,TRINDADE,GO,NaN,2015-12-06,13:10:00,3,2015-12-06 13:10:00
2307,53626,53626,ACIDENTE,AMERICANA,SP,SDAI,2015-12-06,15:00:00,1,2015-12-06 15:00:00
2308,53628,53628,ACIDENTE,AGUAÍ,SP,NaN,2015-12-08,14:30:00,1,2015-12-08 14:30:00
2309,53629,53629,INCIDENTE GRAVE,JALES,SP,SDJL,2015-12-08,10:20:00,0,2015-12-08 10:20:00
2311,60636,60636,INCIDENTE,CAXIAS DO SUL,RS,SBCX,2015-12-08,13:00:00,0,2015-12-08 13:00:00

In [41]:
#Criando novo data frame com as ocorrências do ano de 2015 E mês 3
filtro1 = df.ocorrencia_dia_hora.dt.year == 2015
filtro2 = df.ocorrencia_dia_hora.dt.month == 3
df201503 = df.loc[filtro1 & filtro2]
df201503

,codigo_ocorrencia,codigo_ocorrencia2,ocorrencia_classificacao,ocorrencia_cidade,ocorrencia_uf,ocorrencia_aerodromo,ocorrencia_dia,ocorrencia_hora,total_recomendacoes,ocorrencia_dia_hora
1958,53183,53183,ACIDENTE,AMAPORÃ,PR,NaN,2015-03-02,23:00:00,0,2015-03-02 23:00:00
1959,53120,53120,ACIDENTE,CHAVES,PA,SNXW,2015-03-04,13:30:00,0,2015-03-04 13:30:00
1960,53109,53109,ACIDENTE,CAMPO GRANDE,MS,SSIE,2015-03-05,13:50:00,0,2015-03-05 13:50:00
1961,53112,53112,ACIDENTE,MOGI GUAÇU,SP,NaN,2015-03-06,21:00:00,1,2015-03-06 21:00:00
1962,53152,53152,INCIDENTE GRAVE,RIO DE JANEIRO,RJ,SBRJ,2015-03-10,11:30:00,2,2015-03-10 11:30:00
1963,53167,53167,INCIDENTE,MARABÁ,PA,SBMA,2015-03-10,17:33:00,0,2015-03-10 17:33:00
1964,53596,53596,INCIDENTE,ITAPEMA,SC,NaN,2015-03-10,21:35:00,0,2015-03-10 21:35:00
1965,53149,53149,ACIDENTE,TABATINGA,AM,SBTT,2015-03-11,23:25:00,0,2015-03-11 23:25:00
1966,53148,53148,ACIDENTE,ARARAS,SP,SDEH,2015-03-12,12:40:00,0,2015-03-12 12:40:00
1967,53153,53153,INCIDENTE,PORTO ALEGRE,RS,SBPA,2015-03-13,15:45:00,0,2015-03-13 15:45:00
1968,53154,53154,INCIDENTE,SOROCABA,SP,SDCO,2015-03-13,14:40:00,0,2015-03-13 14:40:00
1969,53238,53238,INCIDENTE,SERRA,ES,NaN,2015-03-13,11:30:00,0,2015-03-13 11:30:00
1970,53189,53189,INCIDENTE,CONFINS,MG,SBCF,2015-03-14,07:20:00,0,2015-03-14 07:20:00
1971,53193,53193,ACIDENTE,CANARANA,MT,NaN,2015-03-14,18:00:00,0,2015-03-14 18:00:00
1972,53164,53164,ACIDENTE,PRINCESA ISABEL,PB,NaN,2015-03-15,18:30:00,0,2015-03-15 18:30:00
1973,53151,53151,INCIDENTE GRAVE,MAUÉS,AM,SWMW,2015-03-16,18:07:00,1,2015-03-16 18:07:00
1974,53168,53168,INCIDENTE,PARÁ DE MINAS,MG,SNPA,2015-03-16,21:05:00,0,2015-03-16 21:05:00
1975,53169,53169,INCIDENTE,BELÉM,PA,SBBE,2015-03-19,03:25:00,0,2015-03-19 03:25:00
1976,53165,53165,INCIDENTE GRAVE,SÃO DESIDÉRIO,BA,NaN,2015-03-20,14:35:00,0,2015-03-20 14:35:00
1977,53188,53188,INCIDENTE,RIO DE JANEIRO,RJ,SBJR,2015-03-20,21:00:00,0,2015-03-20 21:00:00
1978,53184,53184,ACIDENTE,PORTO UNIÃO,SC,NaN,2015-03-22,13:44:00,0,2015-03-22 13:44:00
1979,53178,53178,ACIDENTE,DIAMANTINO,MT,NaN,2015-03-23,17:15:00,0,2015-03-23 17:15:00
1980,53182,53182,ACIDENTE,SANTA LUZIA,MA,NaN,2015-03-23,20:40:00,0,2015-03-23 20:40:00
1981,53166,53166,INCIDENTE GRAVE,RIACHÃO DAS NEVES,BA,NaN,2015-03-24,14:45:00,0,2015-03-24 14:45:00
1982,53170,53170,INCIDENTE,CONFINS,MG,SBCF,2015-03-24,17:57:00,0,2015-03-24 17:57:00
1983,53185,53185,INCIDENTE,CURITIBA,PR,SBCT,2015-03-24,23:01:00,0,2015-03-24 23:01:00
1984,53412,53412,INCIDENTE GRAVE,MACAÉ,RJ,NaN,2015-03-24,16:35:00,0,2015-03-24 16:35:00
1985,53194,53194,ACIDENTE,GUARACIABA DO NORTE,CE,SWBE,2015-03-26,20:30:00,0,2015-03-26 20:30:00
1986,53186,53186,INCIDENTE,BRASÍLIA,DF,NaN,2015-03-27,14:55:00,0,2015-03-27 14:55:00
1987,53179,53179,ACIDENTE,CAIAPÔNIA,GO,NaN,2015-03-28,10:30:00,0,2015-03-28 10:30:00
1988,53180,53180,ACIDENTE,ARAGUARI,MG,NaN,2015-03-28,18:52:00,0,2015-03-28 18:52:00
1989,53190,53190,INCIDENTE,CAMPINAS,SP,SBKP,2015-03-28,16:26:00,0,2015-03-28 16:26:00
1990,53212,53212,INCIDENTE,JUNDIAÍ,SP,SBJD,2015-03-28,17:32:00,0,2015-03-28 17:32:00
1991,53213,53213,INCIDENTE,JUNDIAÍ,SP,SBJD,2015-03-28,15:51:00,0,2015-03-28 15:51:00
1992,53181,53181,ACIDENTE,COLÍDER,MT,NaN,2015-03-29,20:17:00,0,2015-03-29 20:17:00
1993,53187,53187,INCIDENTE,JOINVILLE,SC,SBJV,2015-03-29,18:36:00,0,2015-03-29 18:36:00
1994,53211,53211,INCIDENTE,BAURU,SP,SBBU,2015-03-30,19:40:00,0,2015-03-30 19:40:00

In [42]:
df201503.count()

codigo_ocorrencia           37
codigo_ocorrencia2          37
ocorrencia_classificacao    37
ocorrencia_cidade           37
ocorrencia_uf               37
ocorrencia_aerodromo        21
ocorrencia_dia              37
ocorrencia_hora             37
total_recomendacoes         37
ocorrencia_dia_hora         37
dtype: int64

In [43]:
df201503.groupby(['ocorrencia_classificacao']).codigo_ocorrencia.count()

ocorrencia_classificacao
ACIDENTE           15
INCIDENTE          17
INCIDENTE GRAVE     5
Name: codigo_ocorrencia, dtype: int64

In [44]:
df201503.groupby(['ocorrencia_classificacao']).ocorrencia_aerodromo.count()

ocorrencia_classificacao
ACIDENTE            5
INCIDENTE          14
INCIDENTE GRAVE     2
Name: ocorrencia_aerodromo, dtype: int64

In [45]:
df201503.groupby(['ocorrencia_classificacao']).size()

ocorrencia_classificacao
ACIDENTE           15
INCIDENTE          17
INCIDENTE GRAVE     5
dtype: int64

In [46]:
df201503.groupby(['ocorrencia_classificacao']).size().sort_values()

ocorrencia_classificacao
INCIDENTE GRAVE     5
ACIDENTE           15
INCIDENTE          17
dtype: int64

In [47]:
df201503.groupby(['ocorrencia_classificacao']).size().sort_values(ascending = False)

ocorrencia_classificacao
INCIDENTE          17
ACIDENTE           15
INCIDENTE GRAVE     5
dtype: int64

In [48]:
#Ocorrências do ano de 2012 da região sudeste
filtro1 = df.ocorrencia_dia_hora.dt.year == 2012
filtro2 = df.ocorrencia_uf.isin(['SP','RJ','MG','ES'])
dfsudeste2010 = df.loc[filtro1 & filtro2]
dfsudeste2010

,codigo_ocorrencia,codigo_ocorrencia2,ocorrencia_classificacao,ocorrencia_cidade,ocorrencia_uf,ocorrencia_aerodromo,ocorrencia_dia,ocorrencia_hora,total_recomendacoes,ocorrencia_dia_hora
1,45331,45331,ACIDENTE,GUARULHOS,SP,SBGR,2012-01-06,13:44:00,3,2012-01-06 13:44:00
3,45401,45401,ACIDENTE,SÃO SEBASTIÃO,SP,NaN,2012-01-06,17:00:00,0,2012-01-06 17:00:00
5,52243,52243,INCIDENTE,UBATUBA,SP,NaN,2012-01-06,14:30:00,0,2012-01-06 14:30:00
6,50713,50713,INCIDENTE GRAVE,CAMPINAS,SP,SDAI,2012-01-07,18:15:00,0,2012-01-07 18:15:00
8,45391,45391,ACIDENTE,CONCEIÇÃO DAS ALAGOAS,MG,NaN,2012-01-08,16:00:00,0,2012-01-08 16:00:00
...,...,...,...,...,...,...,...,...,...,...
640,46793,46793,INCIDENTE,SÃO PAULO,SP,NaN,2012-12-28,16:30:00,0,2012-12-28 16:30:00
641,46780,46780,ACIDENTE,SANTA FÉ DO SUL,SP,NaN,2012-12-29,21:00:00,0,2012-12-29 21:00:00
642,46814,46814,INCIDENTE,BELO HORIZONTE,MG,SBBH,2012-12-29,15:10:00,0,2012-12-29 15:10:00
643,46839,46839,ACIDENTE,RIO DE JANEIRO,RJ,NaN,2012-12-29,19:00:00,0,2012-12-29 19:00:00
644,46910,46910,INCIDENTE,UBATUBA,SP,NaN,2012-12-29,20:00:00,0,2012-12-29 20:00:00

In [49]:
dfsudeste2010.groupby(['ocorrencia_classificacao']).size().sort_values()

ocorrencia_classificacao
INCIDENTE GRAVE     31
ACIDENTE            85
INCIDENTE          188
dtype: int64

In [50]:
dfsudeste2010.groupby(['ocorrencia_classificacao', 'ocorrencia_uf']).size()

ocorrencia_classificacao  ocorrencia_uf
ACIDENTE                  ES                1
                          MG               21
                          RJ               14
                          SP               49
INCIDENTE                 ES               11
                          MG               37
                          RJ               53
                          SP               87
INCIDENTE GRAVE           MG                9
                          RJ                5
                          SP               17
dtype: int64

In [51]:
dfsudeste2010.groupby(['ocorrencia_uf', 'ocorrencia_classificacao']).size()

ocorrencia_uf  ocorrencia_classificacao
ES             ACIDENTE                     1
               INCIDENTE                   11
MG             ACIDENTE                    21
               INCIDENTE                   37
               INCIDENTE GRAVE              9
RJ             ACIDENTE                    14
               INCIDENTE                   53
               INCIDENTE GRAVE              5
SP             ACIDENTE                    49
               INCIDENTE                   87
               INCIDENTE GRAVE             17
dtype: int64

In [52]:
dfsudeste2010.groupby(['ocorrencia_cidade']).size().sort_values(ascending = False)

ocorrencia_cidade
RIO DE JANEIRO      36
SÃO PAULO           31
BELO HORIZONTE      25
MACAÉ               17
CAMPINAS            17
                    ..
JUQUIÁ               1
LENÇÓIS PAULISTA     1
LINS                 1
MOGI DAS CRUZES      1
AGUDOS               1
Length: 90, dtype: int64

In [53]:
filtro = dfsudeste2010.ocorrencia_cidade == 'RIO DE JANEIRO'
dfsudeste2010.loc[filtro].total_recomendacoes.sum()

11

In [54]:
dfsudeste2010.groupby(['ocorrencia_cidade']).total_recomendacoes.sum()

ocorrencia_cidade
AGUDOS            0
ALFENAS           0
AMERICANA         0
ANGRA DOS REIS    1
ARARAS            0
                 ..
UBERABA           0
UBERLÂNDIA        0
VARGINHA          0
VILA VELHA        0
VITÓRIA           0
Name: total_recomendacoes, Length: 90, dtype: int64

In [55]:
dfsudeste2010.groupby(['ocorrencia_aerodromo']).total_recomendacoes.sum()

ocorrencia_aerodromo
SBBH    0
SBBP    4
SBBU    0
SBBZ    0
SBCB    0
SBCF    0
SBCP    0
SBDN    0
SBGL    0
SBGR    4
SBGW    0
SBIP    0
SBJD    2
SBJF    0
SBJR    4
SBKP    0
SBME    0
SBMT    2
SBPC    0
SBPR    3
SBRJ    0
SBRP    0
SBSJ    0
SBSP    2
SBSR    0
SBUL    0
SBUR    0
SBVT    0
SDAA    0
SDAI    0
SDAM    1
SDBB    2
SDBK    0
SDBN    0
SDCD    3
SDCO    0
SDIO    0
SDMC    0
SDMV    0
SDPW    0
SDRK    0
SDTB    0
SDTF    0
SDVH    0
SILT    0
SJPT    0
SNHH    0
SNOF    0
SWXQ    0
Name: total_recomendacoes, dtype: int64

In [56]:
dfsudeste2010.groupby(['ocorrencia_aerodromo'], dropna=False).total_recomendacoes.sum()

ocorrencia_aerodromo
SBBH     0
SBBP     4
SBBU     0
SBBZ     0
SBCB     0
SBCF     0
SBCP     0
SBDN     0
SBGL     0
SBGR     4
SBGW     0
SBIP     0
SBJD     2
SBJF     0
SBJR     4
SBKP     0
SBME     0
SBMT     2
SBPC     0
SBPR     3
SBRJ     0
SBRP     0
SBSJ     0
SBSP     2
SBSR     0
SBUL     0
SBUR     0
SBVT     0
SDAA     0
SDAI     0
SDAM     1
SDBB     2
SDBK     0
SDBN     0
SDCD     3
SDCO     0
SDIO     0
SDMC     0
SDMV     0
SDPW     0
SDRK     0
SDTB     0
SDTF     0
SDVH     0
SILT     0
SJPT     0
SNHH     0
SNOF     0
SWXQ     0
NaN     48
Name: total_recomendacoes, dtype: int64

In [58]:
filtro = dfsudeste2010.total_recomendacoes > 0
dfsudeste2010.loc[filtro].groupby(['ocorrencia_cidade']).total_recomendacoes.sum()

ocorrencia_cidade
ANGRA DOS REIS            1
BEBEDOURO                 2
BELO HORIZONTE            3
BOITUVA                   7
BRAGANÇA PAULISTA         4
CAMPINAS                  1
CAMPO FLORIDO             2
CATANDUVA                 3
DRACENA                   1
ELDORADO                  1
ESPINOSA                  2
GUARUJÁ                   3
GUARULHOS                 4
ITANHAÉM                  2
ITU                       1
ITÁPOLIS                  2
JUIZ DE FORA              1
JUNDIAÍ                   2
JUQUIÁ                    3
LENÇÓIS PAULISTA          2
MACAÉ                     4
PARÁ DE MINAS             2
RIO DE JANEIRO           11
SANTA BÁRBARA D'OESTE     2
SÃO PAULO                 8
TARUMIRIM                 1
Name: total_recomendacoes, dtype: int64

In [60]:
dfsudeste2010.loc[filtro].groupby(['ocorrencia_cidade', dfsudeste2010.ocorrencia_dia.dt.month]).total_recomendacoes.sum()

ocorrencia_cidade      ocorrencia_dia
ANGRA DOS REIS         7                 1
BEBEDOURO              7                 2
BELO HORIZONTE         8                 3
BOITUVA                7                 7
BRAGANÇA PAULISTA      4                 4
CAMPINAS               8                 1
CAMPO FLORIDO          2                 2
CATANDUVA              10                3
DRACENA                5                 1
ELDORADO               1                 1
ESPINOSA               7                 2
GUARUJÁ                4                 3
GUARULHOS              1                 3
                       4                 1
ITANHAÉM               4                 2
ITU                    3                 1
ITÁPOLIS               12                2
JUIZ DE FORA           7                 1
JUNDIAÍ                4                 2
JUQUIÁ                 10                3
LENÇÓIS PAULISTA       5                 2
MACAÉ                  2                 4
PARÁ DE MINAS          12                2
RIO DE JANEIRO         1                 2
                       2                 4
                       7                 1
                       8                 3
                       12                1
SANTA BÁRBARA D'OESTE  8                 2
SÃO PAULO              5                 1
                       6                 1
                       7                 2
                       11                2
                       12                2
TARUMIRIM              8                 1
Name: total_recomendacoes, dtype: int64